using System;
using System.Reflection;
using System.EnterpriseServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("Developed for NutriStyle by Dynamic Connections")]
[assembly: AssemblyProductAttribute("Crm 2011 Menu Generation")]
[assembly: AssemblyCopyrightAttribute("2011")]
[assembly: AssemblyTrademarkAttribute("")]

